### ISSUE TITLE
Lack of file

### ISSUE THREAD

**Issue by einspyon** [shaun117/Obstacle-Detection-Proto#1]
Hi, I ran it, but it seems a lack of gkern function, do you have any idea how to solve it ? Thank you

**Comment by shaun117** [comment]
Hi. Sorry for the very ** VERY late response. I changed my computer and I have been looking for files for this project, but I cant find them. Im really sorry :)
But, all the function did was apply the Gaussian Kernel on the images. Please see [https://en.wikipedia.org/wiki/Gaussian_function](url)
